# Generated by Django 5.0.7 on 2024-10-12 08:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='LessonVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='media/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi'])])),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('limit', models.IntegerField(default=16, help_text="O'quvchi sig'imi")),
            ],
        ),
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Guruh raqami. M: FN21', max_length=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('time_lesson', models.TimeField()),
                ('status', models.CharField(choices=[('not_started', 'Boshlanmagan'), ('continue', 'Davom etyapti'), ('ended', 'Tugagan'), ('stopped', "To'xtailingan")], max_length=15)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='online.course')),
                ('days', models.ManyToManyField(to='online.days')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='online.room')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_lesson', models.DateTimeField(auto_now_add=True)),
                ('theme', models.CharField(help_text='Dars mavzusi', max_length=255)),
                ('course_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online.coursegroup')),
            ],
        ),
        migrations.CreateModel(
            name='LessonHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_time', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DateTimeField()),
                ('text', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='lesson/homework/')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='online.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='liked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online.like'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_study', models.BooleanField(default=False)),
                ('courses', models.ManyToManyField(to='online.coursegroup')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('came_to_class', models.DateTimeField(auto_now_add=True, help_text='Darsga kelgan vaqti')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online.lesson')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='online.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=1000)),
                ('file', models.FileField(blank=True, null=True, upload_to='student/homework/')),
                ('lesson_homework', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='online.lesson')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='online.student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField(default=1)),
                ('is_working', models.BooleanField(default=True)),
                ('courses', models.ManyToManyField(to='online.coursegroup')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
